/// Flutter icons RickShare
/// Copyright (C) 2024 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  RickShare
///      fonts:
///       - asset: fonts/RickShare.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class RickShare {
  RickShare._();

  static const _kFontFam = 'RickShare';
  static const String? _kFontPkg = null;

  static const IconData alert = IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData mail = IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData lock_svgrepo_com = IconData(0xe804, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData phone_svgrepo_com = IconData(0xe805, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData disconnect_svgrepo_com = IconData(0xe806, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
